language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.1
xcode_workspace: JsonPatchSwift.xcworkspace
xcode_scheme: JsonPatchSwift
before_install:
  - brew update
  - brew install swiftlint
